.vscode/launch.json, README.md
Random tid-bits to make debugging easier
=> Project setup

timeline-chart/src/components/time-graph-row-element.ts, timeline-chart/src/time-graph-font-controller.ts
Adaptive font size and color determination.
Signed-off-by: Akshay Sharma <akshay.c.sharma@ericsson.com>
=> Render state labels.

timeline-chart/src/layer/time-graph-chart-cursors.ts, timeline-chart/src/layer/time-graph-chart.ts
--States in timeline-chart frozen in place when scrolling
in the horizontal direction.
--Sporadic browser assertions triggered by accessing props (states)
of an undefined selectedRow.
Signed-off-by: Akshay Sharma <akshay.c.sharma@ericsson.com>
=> Bugfixes related to state navigation using the left/right arrow keys.

package.json
Allow PRs such as theia-trace-extension:109 to work
=> update version for new "release"

timeline-chart/src/layer/time-graph-chart.ts
Fixed regression
Signed-off-by: Soukaina Moussaoui <soukaina.moussaoui@polymtl.ca>
=> Timeline chart: Fixed bug in selectRowElement

timeline-chart/package.json, timeline-chart/src/layer/time-graph-chart-cursors.ts, timeline-chart/src/layer/time-graph-chart.ts, yarn.lock
-- Added the mousemove event handler to capture x,y position on the canvas.
-- The x,y position will determine the start from where the zoom should trigger.
-- Recalculated the start and end position.
-- Call the viewRange method with the new coordinates on the canvas.
Note: I have tested this on chrome version (75.0.3770.100) and firefox (79.0 64 bit)
=> Implement zoom in/out and horizontal scrolling using WASD

package.json
Versions 0.0.2 was tagged and done in 2018, then removed, and brought
back, so let's make a first minor release to make sure we don't go back
in versioning times.
Signed-off-by: Geneviève Bastien <gbastien+lttng@versatic.net>
=> Update version to 0.1.0

timeline-chart/src/layer/time-graph-navigator.ts
=> Set Min Width of Navigator

timeline-chart/src/time-graph-container.ts
Addresses: https://github.com/theia-ide/theia-trace-extension/issues/122
=> Programmatic switch between canvas renderer and WebGL

example/src/index.ts, timeline-chart/src/layer/time-graph-chart-cursors.ts, timeline-chart/src/layer/time-graph-chart.ts
=> Change Event listeners from document to Canvas

example/src/test-data-provider.ts, timeline-chart/src/layer/time-graph-chart-cursors.ts, timeline-chart/src/layer/time-graph-chart.ts, timeline-chart/src/time-graph-model.ts
Right Arrow selects next available state.
Left Arrow selects previous available state.
shift+Right/shift+Left selects entire area until next/prev available state.
=> Improve State Navigation using Right/Left Arrow Buttons

timeline-chart/src/layer/time-graph-chart.ts
=> Horizontal Scroll moves timegraph chart in horizontal direction

example/package.json, timeline-chart/package.json
=> Add license field in example and timeline-chart package.json

timeline-chart/src/components/time-graph-row-element.ts
Fixes #59  
Signed-off-by: Ankush Tyagi <ankush.tyagi@ericsson.com>
=> Fix label overflow from the state

timeline-chart/src/components/time-graph-component.ts
Clamp values to range that is acceptable to PIXIjs 5
=> Make all opacity levels work with PIXIjs 5.0

timeline-chart/src/components/time-graph-component.ts, timeline-chart/src/components/time-graph-row-element.ts, timeline-chart/src/layer/time-graph-chart.ts
=> Adjust State's label Position based on view range

example/src/index.ts, timeline-chart/src/components/time-graph-row.ts
=> Revert: Handle onClick event on timegraph row

timeline-chart/src/layer/time-graph-chart.ts
=> Reset fetching flag in a try-finally statement

timeline-chart/src/time-graph-font-controller.ts
Signed-off-by: maria-ericsson <maria.chowdhury@ericsson.com>
=> modify font type and font size for state label text

timeline-chart/src/components/time-graph-row-element.ts
=> add vertical space in-between for states on adjacent rows

.vscode/launch.json, example/public/resources_timegraph_states.json, example/src/index.ts, example/src/test-data-provider.ts, example/src/test-states.ts, timeline-chart/src/components/time-graph-annotation.ts, timeline-chart/src/components/time-graph-row-element.ts, timeline-chart/src/layer/time-graph-chart-cursors.ts, timeline-chart/src/layer/time-graph-chart.ts, timeline-chart/src/time-graph-model.ts, yarn.lock
Add support marker layer with the following styles:
* 'cross'
* 'diamond'
* 'circle'
Size and color can be defined.
Fixes #75
=> add markers as new layer to timeline chart

lerna.json, package.json
=> Fix publishing with lerna v3.22.1

lerna.json, package.json, yarn.lock
This reverts commit 5ff39235c65bf3f25066dea65785891388254c48.
Fixes #83
=> Revert "Bump learna from 2.11 to 3.22.1"

timeline-chart/src/components/time-graph-annotation.ts
=> Draw plus annotation symbol for unknown symbol styles

timeline-chart/src/components/time-graph-row-element.ts
=> Fix label overflow

timeline-chart/src/components/time-graph-axis-scale.ts, timeline-chart/src/layer/time-graph-chart.ts
=> Set limit on zoom-in factor

timeline-chart/src/layer/time-graph-chart-cursors.ts
=> Sync event timestamp with timegraph

doc/documentation.md
Fix some typos and minor edits.
=> Fix some typos in the documentation

timeline-chart/src/layer/time-graph-chart.ts
=> Don't scroll chart when all rows are visible

timeline-chart/src/layer/time-graph-chart.ts
=> Make TimeGraphRow background and gridline spawn full chart width

timeline-chart/src/components/time-graph-annotation.ts
=> Support triangle and inverted-triangle annotation symbols

timeline-chart/src/layer/time-graph-navigator.ts
- Fix navigator disappearing on the right end at high zoom levels
- Fix navigator not reaching the edges of the absolute range
Fixes #108
Signed-off-by: Ilya Mirsky <ilya.mirsky@ericsson.com>
=> Fix issues with the time graph navigator

timeline-chart/src/layer/time-graph-chart.ts
Fixes #104
Signed-off-by: Ankush Tyagi <ankush.tyagi@ericsson.com>
=> Resolves TypeError: Cannot read property viewRangeLength of undefined

timeline-chart/src/layer/time-graph-axis-cursors.ts, timeline-chart/src/layer/time-graph-chart-cursors.ts, timeline-chart/src/layer/time-graph-chart-selection-range.ts, timeline-chart/src/layer/time-graph-navigator.ts
=> Draw initial selection range

timeline-chart/src/components/time-graph-annotation.ts
Helps for triangles and inverted triangles
=> Use Vertical alignment for annotations

timeline-chart/src/layer/time-graph-axis-cursors.ts, timeline-chart/src/layer/time-graph-axis.ts, timeline-chart/src/layer/time-graph-chart-arrows.ts, timeline-chart/src/layer/time-graph-chart-cursors.ts, timeline-chart/src/layer/time-graph-chart-grid.ts, timeline-chart/src/layer/time-graph-chart-selection-range.ts, timeline-chart/src/layer/time-graph-chart.ts, timeline-chart/src/layer/time-graph-layer.ts, timeline-chart/src/layer/time-graph-navigator.ts, timeline-chart/src/time-graph-container.ts, timeline-chart/src/time-graph-unit-controller.ts
When being destroyed, make sure that all children are removed as well as
all event handlers are removed to avoid
Fixes #98
Fixes #120
=> Add APIs to clean-up components and to remove event handlers

example/src/index.ts, timeline-chart/src/components/time-graph-row.ts, timeline-chart/src/components/time-graph-state.ts, timeline-chart/src/layer/time-graph-chart-cursors.ts, timeline-chart/src/layer/time-graph-chart.ts
Also rename related classes, methods and variables.
=> Rename TimeGraphRowElement to TimeGraphStateComponent

timeline-chart/src/layer/time-graph-chart.ts
fixes https://github.com/theia-ide/theia-trace-extension/issues/358
=> Remove the selected state when state is deselected

timeline-chart/src/components/time-graph-state.ts
* Don't create text if the state is smaller than 3 pixels
* If the text is the same, don't make a new text, keep the old one
* If the label is empty, don't create a label
* Delete the bitmaps as they are cleared
=> Accelerate label drawing

example/src/index.ts, example/src/test-data-provider.ts, example/src/test-states.ts, timeline-chart/src/components/time-graph-annotation.ts, timeline-chart/src/layer/time-graph-chart-range-events.ts, timeline-chart/src/layer/time-graph-chart.ts, timeline-chart/src/layer/time-graph-layer.ts, timeline-chart/src/time-graph-model.ts
Signed-off-by: Ankush Tyagi <ankush.tyagi@ericsson.com>
=> Add support for range events in the timeline chart

example/src/index.ts, example/src/test-data-provider.ts, example/src/test-states.ts, timeline-chart/src/components/time-graph-annotation.ts, timeline-chart/src/components/time-graph-rectangle.ts, timeline-chart/src/layer/time-graph-chart-selection-range.ts, timeline-chart/src/layer/time-graph-layer.ts, timeline-chart/src/layer/time-graph-range-events-layer.ts, timeline-chart/src/time-graph-container.ts, timeline-chart/src/time-graph-model.ts
Signed-off-by: Ankush Tyagi <ankush.tyagi@ericsson.com>
=> Add range events layer

example/src/index.ts, example/src/test-data-provider.ts, example/src/test-states.ts, timeline-chart/src/components/time-graph-annotation.ts, timeline-chart/src/components/time-graph-arrow.ts, timeline-chart/src/components/time-graph-axis-cursor.ts, timeline-chart/src/components/time-graph-axis-scale.ts, timeline-chart/src/components/time-graph-component.ts, timeline-chart/src/components/time-graph-cursor.ts, timeline-chart/src/components/time-graph-rectangle.ts, timeline-chart/src/components/time-graph-row.ts, timeline-chart/src/components/time-graph-state.ts, timeline-chart/src/layer/time-graph-chart-arrows.ts, timeline-chart/src/layer/time-graph-chart.ts, timeline-chart/src/layer/time-graph-layer.ts, timeline-chart/src/layer/time-graph-navigator.ts, timeline-chart/src/layer/time-graph-vertical-scrollbar.ts, timeline-chart/src/time-graph-model.ts
Add model to TimeGraphComponent using generics. Store the model for
state, annotation, arrow and row components.
Change TimeGraphStateMouseInteractions to TimeGraphMouseInteractions so
that they can be added to any TimeGraphComponent.
Add element interactions to each annotation component.
Add category to the TimeGraphAnnotation model.
=> Changes to support tooltip for annotations

timeline-chart/src/layer/time-graph-chart.ts
=> Chart freezes when zooming using right mouse button

timeline-chart/src/layer/time-graph-chart.ts
=> Support zooming of timegraph chart from external libs

timeline-chart/src/components/time-graph-annotation.ts, timeline-chart/src/components/time-graph-component.ts, timeline-chart/src/components/time-graph-state.ts, timeline-chart/src/layer/time-graph-range-events-layer.ts
=> Support opacity for states and symbol annotations

doc/documentation.md, timeline-chart/src/layer/time-graph-chart.ts
=> Press esc to cancel mouse zooming

example/src/index.ts, timeline-chart/src/components/time-graph-axis-scale.ts, timeline-chart/src/components/time-graph-component.ts, timeline-chart/src/components/time-graph-grid.ts, timeline-chart/src/components/time-graph-rectangle.ts, timeline-chart/src/layer/time-graph-axis.ts, timeline-chart/src/layer/time-graph-chart-grid.ts, timeline-chart/src/layer/time-graph-layer.ts, timeline-chart/src/time-graph-container.ts
=> update layers based on themes

timeline-chart/src/layer/time-graph-chart.ts
=> Fix Mouse zooming overlay

timeline-chart/src/layer/time-graph-vertical-scrollbar.ts
=> Fix Vertical Scrollbar

timeline-chart/src/layer/time-graph-chart.ts
Instead of skipping fetching of new data when it is already in progress,
use debounce to fetch new data after a 400ms delay without range change.
Fixes Issue #156
Change-Id: Icb74e223bebdd4d43ec2f4add81df38e74702393
=> Use debounce on view range change

timeline-chart/src/layer/time-graph-chart.ts
Enabling support for double clicking a state
- Ideal use case is to be able to zoom in to double click
- Double click mouse interaction on an element is communicated with timegraph-output-component in trace-extension for custom integrations
Implementation
- PixiJS does not support double click interactions, the recommended approach is to make use of a click event and a timeout: https://github.com/pixijs/pixijs/issues/5910
- Using a counter to check if an element has been clicked, followed by a timeout to confirm a double-click within the specified interval
-  Other left-click interactions such as toggling between elements, clicking rows and time-range selection would not trigger double click
- I've added some commenting in the source code to explain my approach. I can remove them when …
=> Support multi-click events

timeline-chart/src/layer/time-graph-chart.ts
Fixes #179
Change-Id: I5e0a96738f27f9191338f6d647f3cff8ad15aab7
=> Ignore duplicate data provider requests and discard obsolete responses

.github/workflows/ci-cd.yml
=> Update publish GitHub action to work with eclipse-cdt-cloud

timeline-chart/src/layer/time-graph-chart.ts
Fixes #201 and https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/754
=> Add element interactions to gap states

timeline-chart/src/layer/time-graph-chart.ts
=> Add API to select and reveal a time-graph row by index

timeline-chart/src/layer/time-graph-chart.ts
To enable this feature, provide a coarse resolution factor that is
higher than 1 to the TimeGraphChart constructor.
When a coarse resolution factor is provided, the first update of time
graph data is made using the coarse resolution. Once this update is
completed, a debounced fine resolution second update is triggered.
The resolution check against provided model is changed to require better
resolution, to prevent a coarse model from being fetched and used to
overwrite a previously fetched fine model.
When no row needs update at coarse resolution, try to update with fine
resolution. This allows the update to trigger when the time graph canvas
width is increased.
=> Support coarse and fine update of time graph data

timeline-chart/src/layer/time-graph-viewport-layer.ts
=> Fix typeError exception in time-graph-viewport-layer.ts

timeline-chart/src/components/time-graph-state.ts
If state has opacity apply it to the font color as well
Signed-off-by: hriday-panchasara <hriday.panchasara@ericsson.com>
=> Apply opacity to state label

.github/workflows/ci-cd.yml
=> Update to node 16 in ci-cd.yml

timeline-chart/src/layer/time-graph-chart.ts
=> Ensure row lines fit width on resize

timeline-chart/src/components/time-graph-row.ts, timeline-chart/src/layer/time-graph-chart.ts
- updateChart() accepts filter-expressions
- If filter-expressions exist perform SAMPLED fetch followed by DEEP fetch
- DEEP search does a row-by-row fetch
=> Enable searching time events in time-graph view

RELEASE, example/package.json, lerna.json, timeline-chart/package.json
=> Release v0.3.1 (Patch)

RELEASE, example/package.json, lerna.json, timeline-chart/package.json
Release a new version of timeline-chart, bundled with a clean version of webpack.
=> Release v0.3.3 (Patch)

timeline-chart/src/layer/time-graph-navigator.ts, timeline-chart/src/time-graph-unit-controller.ts
Add support for absolute range change handlers in unit controller. Make time graph navigator register one such handler so that it can update itself when the absolute range changes.
=> Update time graph navigator on absolute range change

example/package.json, example/src/index.ts, yarn.lock
Fix the example application, that had broken at some point.
Start example application and quickly play with it to confirm it se3ems to work as expected:
```bash
yarn && yarn start
```
Then access the app using a browser: `http://localhost:8081/`
N/A
=> Fix example application

.github/workflows/ci-cd.yml, timeline-chart/package.json, yarn.lock
Update to get rid of this critical severity vulnerability.
see:
https://github.com/dependency-insights/npm/form-data/4.0.0/security?query=org%3Aeclipse-cdt-cloud
Confirm that CI passes. Optionally perform a "yarn why form-data" and confirm that the version pulled is not vulnerable. The version expected with this PR is:
form-data@4.0.4
N/A
=> Update dependencies to get rid of form-data vulnerability
