eclipse-cdt-cloud/timeline-chart

.vscode/launch.json
README.md
example/package.json
package.json
timeline-chart/package.json
timeline-chart/src/components/time-graph-arrow.ts
timeline-chart/src/components/time-graph-axis-scale.ts
timeline-chart/src/components/time-graph-component.ts
timeline-chart/src/layer/time-graph-chart-cursors.ts
timeline-chart/src/layer/time-graph-chart-selection-range.ts
timeline-chart/src/layer/time-graph-chart.ts
timeline-chart/src/layer/time-graph-layer.ts
timeline-chart/src/time-graph-container.ts
yarn.lock

remove deprecated fields "autoResize" and "roundedPixels".
May have a small change in behavior.

timegraph: uplift to PIXI 5.0

---

timeline-chart/src/layer/time-graph-chart.ts

Added a new condition in time-graph-chart.ts that allows to fetch new
data when collapsing or expanding entries. The function updateChart()
allows to update the chart's rows simulteanously when it is called
in the timegraph-output-component.ts in theia-trace-extension.
Signed-off-by: Soukaina Moussaoui <soukaina.moussaoui@polymtl.ca>

SM: Update chart after collapsing or expanding entries in the tree

---

example/package.json
timeline-chart/package.json
timeline-chart/src/components/time-graph-arrow.ts
timeline-chart/src/components/time-graph-axis-scale.ts
timeline-chart/src/components/time-graph-component.ts
timeline-chart/src/components/time-graph-row-element.ts
timeline-chart/src/layer/time-graph-chart-cursors.ts
timeline-chart/src/layer/time-graph-chart.ts
timeline-chart/src/layer/time-graph-layer.ts
timeline-chart/src/time-graph-container.ts
timeline-chart/src/time-graph-font-controller.ts
yarn.lock

This allows support of older browsers without WebGL support.
Signed-off-by: Geneviève Bastien <gbastien+lttng@versatic.net>

Use pixi.js-legacy instead of pixi.js

---

timeline-chart/src/components/time-graph-row-element.ts
timeline-chart/src/layer/time-graph-chart.ts

Set the minimum width of a state to 1 so that small states with negligible widths are visible in the initial zoom level
Signed-off-by: Satish Muddana <satish.muddana@ericsson.com>

States not visible in the initial zoom level

---

timeline-chart/src/layer/time-graph-chart.ts

ctrl+mousewheel and shift+mousewheel should work even when there is no foucs

Fix Timegraphchart's shift+mousewheel and ctrl+mousewheel

---

example/src/index.ts
timeline-chart/src/components/time-graph-row.ts

This feature was woking fine with earlier versions of PIXI
Current PIXI is not able to handle events for elements with opacity 0.
Changed the Opacity as a workaround fix.
Fixes #52 

Handle onClick event on timegraph row

---

example/src/index.ts
timeline-chart/src/layer/time-graph-chart.ts

Retain row and state selection after refresh

---

.travis.yml
lerna.json
package.json
yarn.lock

Multiple security fixes.
Biggest security fix
Addresses CVE-2020-8116:
Prototype pollution vulnerability in dot-prop npm package versions
before 4.2.1 and versions 5.x before 5.1.1 allows an attacker to
add arbitrary properties to JavaScript language constructs such
as objects.

Bump learna from 2.11 to 3.22.1

---

timeline-chart/src/time-graph-container.ts

Resize background as well when resizing canvas.

---

timeline-chart/src/components/time-graph-axis-scale.ts
timeline-chart/src/components/time-graph-grid.ts

The y-pos of the text label should be just below the tick line height.
Drawing the labels should be optional and not done for a TimeGraphGrid
which only needs to draw tick (grid) lines at full height.
Fixes https://github.com/theia-ide/theia-trace-extension/issues/243

Make drawing of TimeGraphAxisScale labels optional and fix their y-pos

---

timeline-chart/src/components/time-graph-axis-scale.ts

Calculate the expected label text width to set the minimum step width.
Fixes https://github.com/theia-ide/timeline-chart/issues/103

Fix overlapping TimeGraphAxisScale labels

---

timeline-chart/src/layer/time-graph-axis.ts
timeline-chart/src/layer/time-graph-chart.ts

The step for zooming by mouse wheel or keyboard is now 80%/125% of
current window range. It no longer depends on mouse cursor y position.
Browser zoom is disabled when using mouse wheel on time axis.

Fix horizontal zoom step ratio

---

doc/documentation.md
timeline-chart/src/layer/time-graph-chart-cursors.ts
timeline-chart/src/layer/time-graph-chart.ts

Allow panning with the mouse with middle button drag or Ctrl+left button
drag. Change the cursor to 'grabbing' while panning is ongoing.
Change the cursor to 'grabbing' when only Ctrl is pressed to indicate
that left button can be used to pan.
Restore the cursor to 'default' when panning is ended by releasing the
mouse button that initiated it, or when the conditions to initiate
Ctrl+left button panning are no longer met.
Prevent time selection with any other button than the left button or
when the Ctrl or Alt key is pressed.

Support horizontal panning with middle button or Ctrl+left button

---

timeline-chart/src/components/time-graph-arrow.ts
timeline-chart/src/components/time-graph-component.ts
timeline-chart/src/layer/time-graph-chart-arrows.ts
timeline-chart/src/layer/time-graph-layer.ts

Arrows are destroyed when the map is updated to not show them and cleanup gpu memory.
Signed-off-by: Arnaud Fiorini <fiorini.arnaud@gmail.com>

Destroy arrows when updating them

---

doc/documentation.md
timeline-chart/src/layer/time-graph-chart-cursors.ts
timeline-chart/src/layer/time-graph-chart.ts

Allow zooming selection with the mouse with right button drag. Change
the cursor to 'col-resize' while zooming selection is ongoing.
Restore the cursor to 'default' when zooming selection is ended by
releasing the right mouse button.
Add a zooming selection transparent overlay while zoom selection is
ongoing. Update the overlay when the view range is changed externally.
Prevent the context menu popup on right mouse click on time graph.
Ensure right mouse button mouse up outside of time graph canvas is
properly detected and handled.

Support horizontal zooming selection with right mouse button

---

timeline-chart/src/layer/time-graph-chart.ts

When TimeGraphChart.maybeFetchNewData() was called while right-mouse
zooming was in progress (for example by navigating with WASD or
Ctrl+mouseWheel), the zoomingSelection rectangle was removed, then
updateZoomingSelection() would try to remove it again before re-creating
a new one, leading to an exception. Clear the zoomingSelection variable
before calling the method since the call to removeChildren() has already
removed it.

Fix TypeError exception in TimeGraphChart

---

timeline-chart/src/layer/time-graph-chart.ts

Use the canvas height instead of layer height.

Fix zooming selection height

---

timeline-chart/src/layer/time-graph-chart.ts

The x-coordinate of the mouseUp event is in the coordinates of the
element under the cursor at the time, which is not necessarily the time
graph coordinates.
Since the mouseEndX variable is updated (correctly) while the mouse is
being moved, just rely on that, and do not update it at mouseUp.

Fix mouse zooming when mouse released outside time graph

---

timeline-chart/src/components/time-graph-axis-scale.ts

Currently the labels of the x-axis are aligned to the left, 5 pixels after their corresponding tick in the axis.
This commit centers the labels according to their ticks. The position of the text is calculated by using the position of the tick, minus half the width of the text.
Before the change:
After the change:
After the change in theia-trace-extension:
Fixes [issue 440 in theia-ide/theia-trace-extension](https://github.com/theia-ide/theia-trace-extension/issues/440).
Signed-off-by: Rodrigo Pinto <rodrigo.pinto@calian.ca>

Center x-axis labels

---

lerna.json
package.json
timeline-chart/LICENSE
yarn.lock

- This change also bumps versions of several other dependencies.
This fixes several dependabot warnings.
- Update publish scripts to use the lerna publish CLI of v4.0.0

Bump lerna from 2.11.0 to 4.0.0

---

example/src/index.ts
example/src/test-arrows.ts
example/src/test-data-provider.ts
example/tsconfig.json
timeline-chart/src/bigint-utils.ts
timeline-chart/src/components/time-graph-axis-scale.ts
timeline-chart/src/components/time-graph-state.ts
timeline-chart/src/layer/time-graph-axis-cursors.ts
timeline-chart/src/layer/time-graph-axis.ts
timeline-chart/src/layer/time-graph-chart-arrows.ts
timeline-chart/src/layer/time-graph-chart-cursors.ts
timeline-chart/src/layer/time-graph-chart-selection-range.ts
timeline-chart/src/layer/time-graph-chart.ts
timeline-chart/src/layer/time-graph-layer.ts
timeline-chart/src/layer/time-graph-navigator.ts
timeline-chart/src/layer/time-graph-range-events-layer.ts
timeline-chart/src/time-graph-model.ts
timeline-chart/src/time-graph-state-controller.ts
timeline-chart/src/time-graph-unit-controller.ts
timeline-chart/tsconfig.json

Timestamps and time durations are changed to be of type 'bigint' instead
of 'number'.
This is done to avoid loss of precision in JavaScript 'number' type for
values above Number.MAX_SAFE_INTEGER (2^53 - 1).
The class BIMath is added to provide some BigInt math utility functions.
The method TimeGraphLayer.getPixels() is renamed to getPixel() since it
returns only one value.
In the time graph axis, fractional scale steps 1.5 and 2.5 are removed
to avoid non-equidistant ticks when zoomed in to nanosecond level, due
to BigInt integer rounding.
The minimum view range is set to 2 ns, to be able to zoom out of it and
to always have at least one time graph axis tick fully visible.

Use BigInt for timestamps

---

timeline-chart/src/layer/time-graph-range-events-layer.ts

The wrong handler was being removed and the leaking handler would cause
exceptions when it got called subsequently.
Change-Id: Ic6386a4478e49f92b57ed75e2f5090a0f31c1b2a

Fix TimeGraphRangeEventsLayer leaking viewRangeChanged handler

---

timeline-chart/src/components/time-graph-axis-scale.ts
timeline-chart/src/time-graph-unit-controller.ts

Add the offset to the time graph unit controller.
Use the offset to make sure that gridlines are set on rounded absolute
times, not rounded relative times to the start of the absolute range.
Calculate the maximum label width using the view range end time instead
of the view range length.
Fixes issue #54
Change-Id: I5ff00c57ae2859703c8eeb8b4db88bc1655d985f

Make gridlines aligned to rounded numbers

---

example/package.json
example/webpack.config.js
yarn.lock

| Package | Current | Updated to |
| --- | --- | --- |
| webpack | 4.22.0 | 5.65.0 |
| webpack-cli | 3.1.2 | 4.9.1 |
| webpack-dev-server | 3.1.10 | 4.7.2 |
The updates resolve Dependabot alerts for the following packages:
- glob-parent;
- ansi-html;
- ansi-regex.
As of now there are also alerts for `json-schema` and `trim-off-newlines`,
but those are dependencies of `lerna` 4.0.0, which does not have an
update yet.
Signed-off-by: Rodrigo Pinto <rodrigo.pinto@calian.ca>

Update Webpack in example project to version 5

---

timeline-chart/src/layer/time-graph-chart.ts

When the time graph canvas width is increased by a resize event, the
data model may no longer be at the appropriate resolution. Invoke the
debounced method to maybe fetch new data, in the same way as is done
when the view range is changed.
Update the data model when the resolution is changed either way (not
only when zooming in) so that an appropriately sized and consistent data
model is always used.
Change-Id: I33373a3fa490ae94e157e20638423de149c91021

Update data model on resize

---

example/package.json
yarn.lock

Resolves Dependabot alerts for:
- node-forge
- ansi-regex
Signed-off-by: Rodrigo Pinto <rodrigo.pinto@calian.ca>

Update webpack-dev-server to v. 4.7.4

---

timeline-chart/src/components/time-graph-axis-scale.ts

Skip rendering vertical lines and tick labels when the chart width is 0,
this avoids division by zero in calculations.

Fix RangeError in TimeGraphAxisScale

---

README.md
timeline-chart/README.md

The repository has been moved to the Eclipse cdt-cloud project and is
now located under the eclipse-cdt-cloud GitHub organization.

Replace theia-ide with eclipse-cdt-cloud references

---

timeline-chart/src/layer/time-graph-vertical-scrollbar.ts

Add moveEnd handler method to document event listeners in the moveStart
method and remove the listener in the moveEnd method.
Fixes #191.

Fix leaking TimeGraphVerticalScrollbarHandle instances

---

timeline-chart/src/components/time-graph-arrow.ts
timeline-chart/src/components/time-graph-component.ts
timeline-chart/src/layer/time-graph-layer.ts
timeline-chart/src/layer/time-graph-navigator.ts

Add a child container to TimeGraphLayer. Add children to the child
container instead of the layer container.
Destroy the layer and its children graphics objects in one call instead
of destroying each child component one-by-one.
When removing all children, destroy the child container in one
operation, destroying all children graphics objects.
The TimeGraphComponent.destroy() method is no longer called recursively
on the child components when destroying the layer or removing all
children. Components are not expected to have any local resources to
release at destruction, other than the graphics object.
Make TimeGraphComponent.destroy() also destroy all children graphics
objects of the component in one operation. Remove the now unnecessary
override of destroy() in TimeGraphArrowComponent.
In …

Destroy TimeGraphLayer in one operation

---

timeline-chart/src/components/time-graph-row.ts
timeline-chart/src/layer/time-graph-chart.ts

When the update flag in maybeFetchNewData() is set to true, it means all
rows must be refreshed (e.g. annotations might have changed). It was
only refreshing the visible rows, and when the other rows later became
visible they were considered valid and not refreshed.
Mark all existing rows as needing to be refreshed by setting their
providedModel object to undefined.

Fix missing row updates

---

timeline-chart/src/components/time-graph-component.ts
timeline-chart/src/layer/time-graph-navigator.ts
timeline-chart/src/layer/time-graph-vertical-scrollbar.ts
timeline-chart/src/time-graph-row-controller.ts

Implements page scrolling on horizontal and vertical scrollbars.  The user can right-click to move the navigator one page in the correct direction.
Updates comments and variable names on previous snap-on-click feature implementation for clarity.
Note: If testing in the timeline-chart example, right click will trigger a context menu.  This will not happen in the trace-viewer-extension, since the default is prevented onContextMenu.  You can disable context menu by opening the browser console and typing `window.oncontextmenu = e => e.preventDefault();`

Page scrolling on vertical and horizontal scrollbars

---

example/src/index.ts
timeline-chart/src/components/time-graph-axis-scale.ts
timeline-chart/src/layer/time-graph-axis.ts

This commit adds support for configurable location of time axis ticks. Currently, the ticks can only be displayed above the time labels in the time axis, which do not make sense UI-wise when we have graphs that are displayed under the time axis. This commit allows the ticks of the time axis to be displayed dynamically either on top or under the time labels by adding a configuration parameter to the TimeGraphAxisScale component, so that developers can position the ticks correctly.
Resolve [Issue 203](https://github.com/eclipse-cdt-cloud/timeline-chart/issues/203) of the Theia Trace Extension. This also relates to [Issue 755](https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/755) of the Theia Trace Extension.

Add support for configurable location of time axis ticks

---

timeline-chart/src/components/time-graph-row.ts

Adds public method TimelineChart#selectRowFromId that sets the selected
row using an ID number as a pointer.
Fixes a bug where background color information wasn't being stored
correctly for time-graph-row.
(I think some linting happened in this PR.  I will comment at the relevant changes.  I can re-create this branch without the linting changes as well.)
Fixes: #774, #772

Selected Row Visibility

---

timeline-chart/src/components/time-graph-component.ts
timeline-chart/src/time-graph-container.ts
timeline-chart/src/time-graph-render-controller.ts
timeline-chart/src/time-graph-row-controller.ts
timeline-chart/src/time-graph-unit-controller.ts

All PIXI.Applications are initiated on the PIXI shared ticker, allowing them to be controlled simultaneously.
PIXI.Ticker.shared is controlled via TimeGraphRenderController and RenderEvents.  RenderEvents fires custom events that are handled by event handlers initiated in the RenderController.
RenderController is created in the UnitController; this is only because we need one RenderController and there is already only one UnitController.
RenderEvents currently fires start-render events in:
- TimeGraphComponent on creation and update.
- StateController when scrolling up/down
Component creation/update handles almost all required rendering events, except scrolling up and down.  This is because there is no vertical scrollbar from timeline-chart being used in theia-trace-extension.  (For …

Prevent Idle Renders

---

timeline-chart/src/layer/time-graph-chart.ts

Adds the method TimeGraphChart#centerRow which has logic to adjust the vertical offset to center a row given it's index.
Fixes: [theia-trace-extension #773](https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/773)

Center rows when selected

---

.gitignore
example/src/index.ts
timeline-chart/src/bigint-utils.ts
timeline-chart/src/components/time-graph-axis-scale.ts
timeline-chart/src/components/time-graph-grid.ts
timeline-chart/src/layer/time-graph-chart-arrows.ts
timeline-chart/src/layer/time-graph-chart-cursors.ts
timeline-chart/src/layer/time-graph-chart-grid.ts
timeline-chart/src/layer/time-graph-chart-layer.ts
timeline-chart/src/layer/time-graph-chart-selection-range.ts
timeline-chart/src/layer/time-graph-chart.ts
timeline-chart/src/layer/time-graph-range-events-layer.ts
timeline-chart/src/layer/time-graph-viewport-layer.ts
timeline-chart/src/time-graph-container.ts
timeline-chart/src/time-graph-state-controller.ts
timeline-chart/src/time-graph-unit-controller.ts

Previously, the canvas/PIXI.Stage was being re-drawn before being re-rendered every time the view changed.  Re-draws are expensive and should be only used when necessary.  
This change implements the concept of having a "world".  The world can be drawn, and changes things like panning / zooming / resizing can be abstracted using the PIXI library. Modifying PIXI variables like position and scale can be used to modify what is shown instead of clearing the canvas of all PIXI objects and re-drawing them in the correct place.
Current implementation only properly handles horizontal panning, or moving left and right.  Other actions like zooming, window resize, and others, still require a manual re-draw.  These can be implemented in the future.
1. `worldRange` is added.
2. `worldRenderFactor` …

Viewport implementation

---

timeline-chart/src/layer/time-graph-chart.ts

To remove the zooming selection layer from the timeline chart, it is necessary to 1) remove the zooming selection object from the graph, and 2) delete the zooming selection object to reset it. Currently, when fetching new data, the code only performs step 2), but not 1). This leads to an issue where the zooming selection layer is not removed when users select a new zooming selection after zooming out. This commit adds step 1) so that when new data is fetched, the zooming selection is drawn and removed properly.
Fixes [Trace Compass Issue 839](https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/839)
Signed-off-by: Hoang Thuan Pham <hoang.pham@calian.ca>

Remove zooming selection display object when fetching new data.

---

timeline-chart/src/components/time-graph-state.ts

Currently, when the timeline chart renders text labels for states, it deletes all existing labels, then creates new labels, and adds them to the graph. This is not efficient and makes rendering of the labels sluggish when zooming in and out of the graph. This commit removes the code that delete the text labels objects on every re-render, and updates the text content of the labels instead of re-creating them.
Fixes #225.
Signed-off-by: Hoang Thuan Pham <hoang.pham@calian.ca>

Improve rendering for text labels

---

timeline-chart/src/time-graph-font-controller.ts

When the timeline chart is zoom in/out, the label of each state will be modified to fit the width of the state. When the width of the state is smaller than the width of the label, the text is truncated. To determine how much text is truncated, the timeline chart uses the ratio of `width of label text / width of state`.  However, since the width of each charater is different, this ratio does not well-represent how much text can be displayed in the label, causing text to overflow out of the state. The solution is to use a 
`monospace` font, in which all characters are of the same width.
This commit changes the font-family of the labels from `Verdana` to  `monospace`. With this change, the browser will default to the monospace font of the OS and make the texts fit within the states.
Fixes …

Use monospace font for state labels

---

timeline-chart/src/layer/time-graph-chart.ts

Fixes https://github.com/eclipse-cdt-cloud/theia-trace-extension/issues/895
Previously, world range was not getting updated for fine-resolution updates.  Zooming in was always a fine-resolution update, so the world range stayed the same.  This is why nbTimes was becoming so large while zooming: the entire trace was always being fetched.
It's fine if we update the world range for fine-resolution updates.  I thought this was an optimization, but it doesn't actually do anything (besides bug the code).
World range now updates on fine-resolution calls to maybeFetchNewData and the bug seems to be resolved. 

Issue #895 Fix

---

timeline-chart/src/layer/time-graph-chart-cursors.ts
timeline-chart/src/layer/time-graph-markers-chart-cursors.ts

Implements functionality to navigate through markers by using "," and ".".
Fixes the TODO's listed in PR #237.  Uses class inheritance to remove duplicate code.  Uses different algorithm for computing next/previous state, since marker states don't always come in a time-sorted array.  

Marker navigation

---

timeline-chart/src/components/time-graph-state.ts
timeline-chart/src/time-graph-font-controller.ts

Currently, the timeline-chart creates a BitMapText object to measure the width of the label text for every state, before actually rendering it. If a label text does not fit within its state, the BitMapText object is not used, and will remain there until the chart deletes the state. This hogs the performance of the timeline chart, especially when a large number of states need to be removed, because the chart needs to delete the BitMapText objects as well.
This commit uses PIXI.TextMetrics.measureText() as a faster alternative to measure the text label width. The advantage of this method is that it is a static method, which requires no object construction. Thus the timeline-chart will only create and remove BitMapText objects that are actually used to display label texts. The disadvatage is …

Use TextMetrics to measure label text width before rendering

---

.github/workflows/ci-cd.yml

The version of ubuntu is deprecated. Use 20.04 instead.
Also upgrade node version.

Update ubuntu version and node version in ci-cd.yml

---

lerna.json

We hope this will permit publishing to `npm` using an automation token.
See: https://github.com/lerna/lerna/issues/2788#issuecomment-776726711

[lerna] option verifyAccess to false

---

package.json

This is to make sure -next versions sort properly so 'yarn upgrade' upgrades to valid newer versions.
fixes #253

releng: Include date in version string for next versions

---

doc/documentation.md
timeline-chart/src/components/time-graph-grid.ts
timeline-chart/src/components/time-graph-state.ts
timeline-chart/src/layer/time-graph-chart-arrows.ts
timeline-chart/src/layer/time-graph-chart-cursors.ts
timeline-chart/src/layer/time-graph-chart-grid.ts
timeline-chart/src/layer/time-graph-chart-selection-range.ts
timeline-chart/src/layer/time-graph-chart.ts
timeline-chart/src/layer/time-graph-viewport-layer.ts
timeline-chart/src/time-graph-container.ts
timeline-chart/src/time-graph-state-controller.ts
timeline-chart/src/time-graph-unit-controller.ts

This commit uses PIXI.Container scale property to rescale the chart after each zoom in/zoom out to instead of the using the manually repositioning each elements in the chart to improve the performance of the timeline chart. The scale of the time-graph-chart is changed everytime the view range changes, and is reset once the server has replied to the front-end.
This commit removes the method updateScaleAndPosition(), which was used to manually rescaling the chart.
There are 3 use cases that are affected by this change:
[1] Zooming in and out using the mouse wheel
[2] Zooming in using the selection tool (right-click and drag)
[3] Zooming in using the action buttons (+/-) on the top right of the chart.

Rescale timeline-chart post zoom using PIXI.Container scale property

---

timeline-chart/src/layer/time-graph-chart.ts
timeline-chart/src/time-graph-state-controller.ts

Currently, scaling state happens when the view range changes. This is not the expected behaviour. States should only be scaled when the scale factor changes. This commit moves the function that scales the states from the view range change handlers to the scale factor change handlers. This will also help make better code isolation for unit tests.

Make scaling state a handler of onScaleFactorChange event

---

timeline-chart/src/components/time-graph-annotation.ts
timeline-chart/src/layer/time-graph-chart.ts

- Add the scale factor to the constructor and as a field of a time graph annotation. Use this scale factor when rendering the annotation.
- Rename scaleStateLabels() to scaleComponents() and make the method scale both state labels and annotations. This prevents annotations from being stretched or compressed on zoom.

Scale annotations on change of time graph scale factor

---

lerna.json
package.json
timeline-chart/package.json
yarn.lock

Upgraded lerna from v4.x to 7.x, getting rid of several big security vulnerabilities, that were present in the older version.
Repo build should be successful and the example application should run as expected.  
The publishing "script" entries for this repo are identical to the ones used in `theia-trace-extension`, and so i have not gone through the process of testing publishing using a local registry. I can do it, if deemed necessary.
Before this PR (master):
After:

[lerna] upgrade to recent version

---

.github/workflows/ci-cd.yml
.github/workflows/release.yml
README.md
RELEASE
doc/documentation.md
package.json
timeline-chart/README.md
timeline-chart/package.json

The new release workflow uses action "pipe-cd/actions-gh-release". This action uses file RELEASE in the root. When that file is modified in a PR, and contains a new release tag, it will trigger a release upon the PR being merged. The action will create a git tag in the repo and the corresponding GitHub release, containing auto-generated release notes, that can be later edited by a committer.
The new release will in turn trigger the new "publish-latest" job (ci-cd workflow), which will publish the new version of the package to npm.
Also made misc improvements, e.g. in the package.json, README, ...
Note: it's expected that the "GitHub release" job will fail for now.
To test locally using e.g. `verdaccio`: 
Look at the release procedure added in the root (developer's) README, section …

CI publish: Add release workflow/job, publish-latest job

---

RELEASE
example/package.json
lerna.json
timeline-chart/package.json

Trigger a release (v0.3.0) to confirm our automated release/publish infrastructure is working as intended. This was done following these [instructions (README.md)](https://github.com/eclipse-cdt-cloud/timeline-chart/blob/master/README.md#publish-latest--release)
Upon merging this PR, we expect: 
- a `v0.3.0` GitHub release is created, with associated release notes (auto-generated)
- a `v0.3.0` git tag is created
- a `timeline-chart@0.3.0` package is published to npm

Release v0.3.0 (Minor)

---

timeline-chart/.npmignore

Fixes #275
This commit adds a `.npmignore` file to help control what's not included in the `timeline-chart` npm package. With it, we now skip packaging the test, which should reduce the package size considerably.
Approx resulting package size (unpacked): from ~160M to ~600k:

Do not package tests

---

.github/workflows/ci-cd.yml
.github/workflows/license-check-workflow.yml
README.md

update to node 18

---

timeline-chart/package.json
yarn.lock

The yarn upgrade gets rid of a known vulnerability in webpack < 5.94.0
Since this repo has not yet adopted nodejs 20, pinned rimraf dependency to a version that works with node 18.
After this PR is merged, we will need to publish a new package to npm and adopt the new version in `traceviewer-react-components'

Perform yarn upgrade, upgrade webpack

---

.github/workflows/ci-cd.yml

This one case was missed when we updated to node 18 a while ago.

Use node 18 for publish-latest job

---

RELEASE
example/package.json
lerna.json
timeline-chart/package.json

Let's try this again - publish for v0.3.3 failed because a dependency required node 18 and the workflow was using node 16... Should work now.

Release v0.3.4 (Patch)

---

timeline-chart/src/layer/time-graph-chart.ts
timeline-chart/src/time-graph-state-controller.ts

Clamp the computed requested world range (which adds a buffer to the left and right of the view range) to the limits of the absolute range.
This prevents unnecessary row updates because the row's provided model range is always clamped.
Reject row data received during full search for an outdated world range.

Clamp computed world range to absolute range

---

timeline-chart/src/layer/time-graph-chart.ts

If a state is filtered out, don't create a new state for it.  Filtered states are represented by tags = 4, and filtered and dimmed are represented by tags = 5.
Signed-off-by: William Yang <william.yang@ericsson.com>

Filter gap states.

---

timeline-chart/src/layer/time-graph-chart.ts

When rows models are fetched from the data provider, if any requested row is not returned, consider that this row has been excluded by EXCLUDE filtering, and remove its row component. Reposition all remaining rows when rows are excluded.
Keep track of excluded rows and of the world range that was used to exclude them.
During fullSearch with EXCLUDE filter, add previously excluded rows to the request to determine if they should reappear.
When complete update is requested, remove row components that are not visible because they would otherwise not be updated and their states could linger at the wrong position.
After a fullSearch update is completed, restart another request in case new rows have become visible due to space left by newly excluded rows.
Skip coarse update when EXCLUDED filter …

Hide excluded rows

---

timeline-chart/src/layer/time-graph-chart.ts

Only clear excluded rows if the EXCLUDED filtering expressions have changed. This prevents unnecessarily redoing filtering of rows when only the search string has changed.
Determine the list of rows that have only changed y-position, for example due to collapsing of preceding rows. If these rows do not need to be fetched because their current model is valid, then rebuild the rows using their current model to update each child element's position.
If no rows at all need to be fetched but there were some moved rows, perform a fetch to update the arrows which may have changed their start and/or end position.
Remove unused code for updating and removing of gap states, as the states and gaps are always added from scratch when updating a row. Remove the reference to gap state components in the …

Fix time graph filtering and collapsing

---

package.json
yarn.lock

Lerna 7.x seems to be a dead branch, so we need to use 8.x to get e.g. security updates. The upgrade looks to be seamless - I briefly tested using the new lerna to generate a release and got exactly the same result as with 7.x.

Upgrade to lerna 8.x, perform yarn upgrade

---

timeline-chart/src/time-graph-container.ts

Added an entry to TimeGraphContainerOptions, that the caller can use to request that no WebGL context be used for the new TimeGraphContainer:
`noWebGl?: boolean`
This can be used when the container is known in advance to be lightweight in terms of rendering, and that using one of a limited number of available WebGL contexts for it, is not the potential performance gain.
Confirm CI passes
Once this is merged and released, consumer like the react components package in theia-trace-extension can be updated to use this, declining that a WebGL context be used for some of the time graph containers it creates, thus sparing the limited WebGL contexts. See Draft PR: https://github.com/eclipse-cdt-cloud/theia-trace-extension/pull/1206

[WebGL] Make it optional to use WebGL when creating TimeGraphContainer
